pretrained: OuteAI/Lite-Oute-1-65M-Instruct

seed: 42
device: "cuda"
output_dir: "./pickem-smol"
wandb: True
wandb_project: pickem-smol
train_dataset: awilliamson/cfb-qwen
eval_dataset: awilliamson/cfb-qwen
compile: False
precision: "bf16"

batch_size: 2
gradient_accumulation_steps: 2
gradient_checkpointing: True
use_adam: False

attention_dropout: 0.1
learning_rate: 1e-4
adam_beta1: 0.9
adam_beta2: 0.999
epochs: 5
warmup: 0.03

save_interval: 1000
eval_interval: 500
eval_steps: 5