seed: 42
device: "cuda"
output_dir: "./pickem-std"
wandb: False
wandb_project: pickem-std
train_dataset: awilliamson/football
eval_dataset: awilliamson/football
compile: False
precision: "bf16"
length_sample: False

batch_size: 128
gradient_accumulation_steps: 2
gradient_checkpointing: True
use_8bit_adam: False

attention_dropout: 0.1
learning_rate: 1e-4
adam_beta1: 0.9
adam_beta2: 0.999
epochs: 5
warmup: 0.03

save_interval: 750
eval_interval: 250
eval_steps: 25