seed: 42
device: "cuda"
output_dir: "./pickem-qwen"
wandb: False
wandb_project: pickem-qwen
train_dataset: awilliamson/cfb-qwen
eval_dataset: awilliamson/cfb-qwen
compile: False
precision: "bf16"

batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: True
use_adam: True

attention_dropout: 0.1
learning_rate: 1e-4
adam_beta1: 0.9
adam_beta2: 0.999
epochs: 5
warmup: 0.03

save_interval: 500
eval_interval: 100
eval_steps: 10